---

- name: "set facts"
  set_fact:
    role_file_source: "{{ role_path }}/files/docker/"
    role_comment: "( {{ docker_container_name | default('toughday') }} )"

- name: ensure container is started {{ role_comment }}
  docker_container:
    state: started
    name: "{{ docker_container_name }}"
    image: "{{ docker_image }}{% if docker_image %}:{% endif %}{{ docker_image_tag }}"
    env:
      TZ: "{{ docker_timezone }}"
    command: "{{ docker_command }}"
    docker_host: "{{ docker_host }}"
    tty: "true"
    detach: "false"
    cleanup: "true"
    volumes:
      - /tmp:/tmp
  register: docker_output
  tags:
    - docker-container

- name: test output {{ role_comment }}
  debug:
    msg:
      - "{{ docker_output.ansible_facts.docker_container.Output }}"
  tags:
    - toughday-dam

- name: remove toughday container {{ role_comment }}
  docker_container:
    name: "{{ docker_container_name }}"
    state: absent
    docker_host: "{{ docker_host }}"
  tags:
    - toughday-dam
